version: '2.1'
orbs:
  aws-eks: circleci/aws-eks@2.2.0
  kubernetes: circleci/kubernetes@1.3
jobs:
  create-cluster:
    docker:
      - image: 'cimg/python:3.10'
    steps:
      - checkout
      - run:
          name: install aws cli and configure credential
          command: |
            pip install awscli
            aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
            aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
            aws configure set aws_session_token $AWS_SESSION_TOKEN
            aws configure set region $AWS_DEFAULT_REGION
      - aws-eks/create-cluster:
          cluster-name: cluster-project-5
          aws-region: us-east-2
          # node-ami: ami-052efd3df9dad4825
          node-type: t2.micro
          nodes-min: 1
          nodes-max: 2
          ssh-public-key: project-3-keypem
      # - run:
      #     name: create node group
      #     command: |
      #       eksctl create nodegroup --config-file=infrastructure/node_group.yaml

  # test-cluster:
  #   docker:
  #     - image: 'cimg/python:3.10'
  #   parameters:
  #     cluster-name:
  #       description: |
  #         Name of the EKS cluster
  #       type: string
  #   steps:
  #     - kubernetes/install:
  #         kubectl-version: v1.22.0
  #     - aws-eks/update-kubeconfig-with-authenticator:
  #         cluster-name: << parameters.cluster-name >>
  #     - run:
  #         command: |
  #           kubectl get services
  #         name: Test cluster
workflows:
  deployment:
    jobs:
      - create-cluster
