
Resources:
  ClusterRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: 
                - eks.amazonaws.com
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
  PolicyClusterRole:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Effect: Allow
            Action:
              - eks:*
            Resource: '*'
        Version: 2012-10-17
      PolicyName: PolicyCluster
      Roles:
        - !Ref ClusterRole

  ClusterApplication:
    Type: AWS::EKS::Cluster
    Properties:
      Name: Cluster-Application-1
      RoleArn: !GetAtt ClusterRole.Arn
      ResourcesVpcConfig:
        SubnetIds:
          - subnet-0ed29f98c05f7c4e1
          - subnet-0d9a4faa28bfb6561
      Logging:
        ClusterLogging:
          EnabledTypes:
            - Type: api
            - Type: audit