
Resources:
  NodeGroupRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: 
                - ec2.amazonaws.com
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
        
  SecurityGroupId:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: 'learning-eks'
      GroupDescription: Allow port 22 and port 3030.
      SecurityGroupIngress:
        - Description: "SSH access"
          IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

  LauchTemplateId1:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:        
      # ToDo: AMI ID of Ubuntu Linux machine. Too get one, try creating a VM from the web console. 
      ImageId: ami-09d56f8956ab235b3
      # ToDo: Change the key-pair name, as applicable to you. 
      KeyName: project-3-keypem
      SecurityGroups:
      - Ref: SecurityGroupId
      InstanceType: t2.micro
      BlockDeviceMappings:
      - DeviceName: /dev/xvda
        Ebs:
          VolumeSize: '10'

  LauchTemplateId2:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: EKSTemplateLaunch
      LaunchTemplateData:
        BlockDeviceMappings:
          - DeviceName: /dev/xvda
            Ebs:
              DeleteOnTermination: true
              VolumeSize: 10
              VolumeType: gp2
        ImageId: ami-09d56f8956ab235b3
        InstanceType: t2.micro
        KeyName: project-3-keypem
        SecurityGroupIds:
          - !GetAtt SecurityGroupId.GroupId

  NodeGroupResource:
    Type: AWS::EKS::Nodegroup
    Properties:
      Subnets:
        - subnet-0ed29f98c05f7c4e1
        - subnet-0d9a4faa28bfb6561
      NodeRole: !GetAtt NodeGroupRole.Arn
      ClusterName: Cluster-Application-1
      NodegroupName: Worker-Node-1
      RemoteAccess:
        Ec2SshKey: project-3-keypem
        SourceSecurityGroups:
          - !Ref SecurityGroupId
      LaunchTemplate:
        Name: EKSTemplateLaunch
        Version: !GetAtt LauchTemplateId2.LatestVersionNumber
      Taints:
        - Effect: NO_SCHEDULE
          Key: taintkey
          Value: taintvalue
      Labels: 
        Key1: Value1
      ScalingConfig:
        MinSize: 2
        DesiredSize: 3
        MaxSize: 4